version: '3'

services:
  database:
    image: postgres:latest
    container_name: cart_database
    restart: "no"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}" ]
      interval: 2s
      timeout: 2s
      retries: 3

  api:
    depends_on:
      database:
        condition: service_healthy
    build: .
    container_name: cart_api
    restart: "no"
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DB_PORT}