version: '3'

services:
  database:
    image: postgres:latest
    container_name: cart_database
    restart: "no"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./internal/database/database.sql:/docker-entrypoint-initdb.d/database.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U pgadmin -d cart_api" ]
      interval: 2s
      timeout: 2s
      retries: 3

  api:
    depends_on:
      database:
        condition: service_healthy
    build: .
    container_name: cart_api
    restart: "no"
    ports:
      - ${API_PORT}:${API_PORT}