version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: cart-db
    restart: unless-stopped
    ports:
      - ${DB_PORT}:${DB_PORT}
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - cart-network

  api:
    depends_on:
      mongo:
        condition: service_healthy
    build: .
    container_name: cart-api
    restart: unless-stopped
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      - cart-network

networks:
  cart-network:
    external: true