version: '3'

services:
  database:
    image: postgres:latest
    container_name: cart_database
    restart: "no"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./internal/database/database.sql:/docker-entrypoint-initdb.d/database.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U pgadmin -d cart_api" ]
      interval: 2s
      timeout: 2s
      retries: 3

  api:
    depends_on:
      database:
        condition: service_healthy
    build: .
    container_name: cart_api
    restart: "no"
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=${DATABASE_HOST}
      - DB_USER=${DATABASE_USER}
      - DB_PASSWORD=${DATABASE_PASSWORD}
      - DB_NAME=${DATABASE_NAME}