version: '3.8'

services:
  api:
    depends_on:
      psql:
        condition: service_healthy
    build: .
    container_name: cart-api
    restart: unless-stopped
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      - cart-network

  psql:
    image: postgres:latest
    container_name: cart-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5433:${DB_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 2s
      timeout: 2s
      retries: 3
    networks:
      - cart-network

networks:
  cart-network:
    external: true